name: exam-score-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - numpy