name: MLflow Project CI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install mlflow
          pip install -r Workflow-CI/MLProject/conda.yaml
      - name: Run MLflow Project
        run: |
          cd Workflow-CI/MLProject
          mlflow run . --env-manager=local
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: Workflow-CI/MLProject/mlruns/